# Generated by Django 5.0.6 on 2024-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('date_created', models.CharField(max_length=50, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
