# Generated by Django 5.0.6 on 2024-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flowchart_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='flowcharts',
            field=models.ManyToManyField(blank=True, related_name='flowcharts', to='api.flowchart'),
        ),
    ]
