# Generated by Django 5.0.6 on 2024-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_flowchart_description_user_flowcharts'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flowcharts/'),
        ),
    ]
