# Generated by Django 5.0.6 on 2024-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='api.lecture'),
        ),
    ]
